{"division": "Agriculture and life science", "name": ["Michael John Weaver"], "title": ["Professor/Director, VTPP"], "email": ["\n\t mweaver@vt.edu"], "phone": "540-231-6543", "department": " Virginia Tech Pesticide Programs 302 Agnew Hall (0409) Blacksburg,  VA  24061 USA", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Thomas P Kuhar"], "title": ["\n\tProfessor  "], "email": ["\n     tkuhar@vt.edu"], "phone": "540-231-6129 540-231-6129 \n(Office)", "department": " Department of Entomology (MC 0319), Virginia Tech 170 Drillfield Drive Blacksburg,  Virginia  24061 United States", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Igor V Sharakhov"], "title": ["Associate Professor"], "email": ["\n\t igor@vt.edu"], "phone": "(540) 231-7316", "department": "Entomology 203 Fralin Biotechnology Center Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Paul Marek"], "title": ["Assistant Professor"], "email": ["\n     pmarek@vt.edu"], "phone": "(540) 231-5653", "department": "503 Latham Hall Virginia Tech Blacksburg, VA 24061 United States", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Dini Miller"], "title": ["Professor"], "email": ["\n\t dinim@vt.edu"], "phone": "(540) 231-4918", "department": "Entomology Dodson Pest Managment Lab. Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Kevin M Myles II"], "title": ["Associate Professor"], "email": ["\n\t mylesk@vt.edu"], "phone": "(540) 231-6158", "department": "Fralin Life Science Institute 360 West Campus Drive Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Sally L Paulson"], "title": ["Assoc Professor"], "email": ["\n\t spaulson@vt.edu"], "phone": "(540) 231-8035", "department": "Entomology 211 Price Hall Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["L. T. Kok"], "title": ["Professor Emeritus of Entomology"], "email": ["\n     ltkok@vt.edu"], "phone": "(540) 231-6341", "department": "Entomology (0319) Price Hall, 216, Virginia Tech 170 Drillfield Dr. Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Scott Salom"], "title": ["Professor"], "email": ["\n\t salom@vt.edu"], "phone": "(540) 231-2794", "department": "Entomology 210 Price Hall Blacksburg, VA 24061", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Carlyle C Brewster"], "title": ["\n\t  "], "email": ["\n     carlyleb@vt.edu"], "phone": "(540) 231-6826", "department": " Department of Entomology, 202 Price Hall, Virginia Tech, 170 Drillfield Drive Blacksburg,  VA  24061 USA", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Troy D Anderson"], "title": ["\n\tAssistant Professor  "], "email": ["\n     anderst@vt.edu"], "phone": "(540) 231-1862", "department": "Entomology 216 Price Hall 170 Drillfield Drive Blacksburg, VA 24061 United States", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Zachary N Adelman"], "title": ["Associate Professor"], "email": ["\n     zachadel@vt.edu"], "phone": "(540) 231-6614", "department": "Department of Entomology 305 Fralin Life Science Institute, Virginia Tech 360 West Campus Dr Blacksburg, VA 24061 United States", "institution": "Virginia Tech"}
{"division": "Agriculture and life science", "name": ["Doug Pfeiffer"], "title": ["\n\tProfessor  "], "email": ["\n\t dgpfeiff@vt.edu"], "phone": "(540) 231-4183", "department": "Entomology 205C Price Hall Blacksburg, VA 24061", "institution": "Virginia Tech"}
